### ISSUE TITLE
Market Mixie

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Mixie#102]
Create interstijg content that will drive leads to mixie and gain some users 

## TODO:
- [ ] Create sole short videos 
- [ ] Create some articles 
- [ ] Share my progress on Twitter with the hashtag #buildinpublic
