### ISSUE TITLE
ADs, SEO, Settings, fixing small bugs

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Mixie#75]
## TODO:
- [x] Add Ad's #53 
- [x] #68
- [x] Security improvements and finding vulnerabilities
- [x] Add feedback form 
- [x] Make the main `layout.tsx` file server rendered and make a providers file for things like NextAuth, Global theme, tRPC, etc
- [x] Fix nav bar hamburger on mobile 
- [x] [Adding Eslint rules for accessibility](https://nextjs.org/docs/architecture/accessibility)

### SEO:
https://squoosh.app/
https://maskable.app/
- [x] Google search console 
- [x] recipeJsonLd fix to be in `<head></head>` 
- [x] compress favicon, maskable images
- [x] Open graph images
- [x] Every page has Metadata constructing 

### User:
- [x] Google signin
- [x] bookmarks
- [x] Customization page
- [x] Prefences page
- [x] Generate a name for email signIn users 

### Legal:
- [x] Terms and services 
- [x] Updates to privacy policy if needed (Analytics, user info)

### API's
- [ ] sending user data over API, how to keep this secret 
- [x] Add `try`/`catch` statements to create and edit endpoints, along with proper responses back for all errors 

**Imports:**
- [ ] Make it so users can import from text e.g paste a recipe in from instagram or something like: https://www.instagram.com/p/CuNs5e6pRXw/ in the desciption there is a recipe so maybe handle imports like that, might integrate NLP 

### Recipe page:
- [x] Better ingredient chip searching 
- [x] Recipe sharing #26

**Sharing:**
- Instagram: 
    - Sharing link: https://www.facebook.com/sharer/sharer.php?u=${url}
    - docs: [Instagram docs]()
- Threads
    - Sharing link: 
    - docs: [Treads docs]()
- Twitter : 
    - Sharing line: `https://twitter.com/intent/tweet?url=${url}&text=${title}&via=Meally&hashtags=${}`
    - docs: [Twitter docs](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent)
- Facebook 
    - Sharing link: https://www.facebook.com/sharer/sharer.php?u=${url}
    - docs: [Facebook docs](https://developers.facebook.com/docs/plugins/share-button/)
- Pintrest
    - Sharing link: 
    - docs: [Pintrest docs]()
- Printing - something that will open the printing view
- Email
    - Sharing link: 
    - docs: [Email docs]()
- Copy link - simple button 

### Recipe form:
- [x] Controls (preview, publish, save) to not obscure fields to much on mobile 

### Bugs:
- [x] No profile picture for users singing in with email

**Comment by Eirfire** [comment]
mainly implemented in #91
