### ISSUE TITLE
Inbox for users 

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Mixie#94]
Create an inbox for users so they can keep up to date on what is happening across the app, certain updates will be sent out in emails e.g group invites, recipe updates/suggestions, etc

## TODO:
- [ ] Create UI (will be an inbox icon next to the profile)
- [ ] Add drop-down to see the inbox
- [ ] Add inbox page/dialog to view them all 
- [ ] Add accepting certain inbox tasks
