### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Mixie#95]
Groups are going to be a vital part of Mixie, this will allow the user to work with their friends, family, co-workers and many more even complete strangers. 

With a group, you will be able to bookmark/add recipes to that group in which you can make comments and edit it, along with your own rating of the recipe when adding it to a group. you can also add your drafts to the group for the group to suggest changes.

## TODO
- [ ] Figure out data structures 
- [ ] Figure out the user flow and UX
- [ ] Design UI

### Features
- [ ] Bookmarking / Adding recipes to a group
- [ ] Adding your drafts to the group 
- [ ] Editing / Customizing groups
- [ ] Ability to invite users to a group which will be to the inbox (#94) and sent via email
