### ISSUE TITLE
Bookmarking & collections

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Mixie#97]
Bookmarking recipe is going to be a huge part in Mixie and will be a big drawer for people when using the app.

When bookmarking you will be able to have collections and put recipes in that collection.

![image](https://github.com/Eirfire/Mixie/assets/77374574/ae69c603-1801-458c-a563-64ddab5f39a8)

## TODO
- [x] Having heart icon go solid on bookmarked
- [x] Bookmark dialog for adding to a collection 
- [x] Add the ability to have collections
- [ ] Editing of collections 
- [ ] Removing bookmarks 
- [ ] deleting of collections

**Comment by Eirfire** [comment]
Satisfied in #103
